#!/usr/bin/env python3
"""Prepare hash-locked vendor inputs; never modify the extracted Flyme originals."""
import argparse
import hashlib
import json
import re
from pathlib import Path
import shutil
import subprocess


def digest(data):
    return hashlib.sha256(data).hexdigest()


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('android', type=Path)
    args = parser.parse_args()
    root = args.android.resolve()
    device = root / 'device/meizu/m86'
    vendor = root / 'vendor/meizu/m86'
    lock = json.loads((device / 'independent/blobs.lock.json').read_text())
    # Validate every original before writing any generated file.
    for relative, expected in lock['inputs'].items():
        if digest((vendor / relative).read_bytes()) != expected:
            raise SystemExit(f'Original input hash mismatch: {relative}')
    # Device workarounds must follow vendor onto an unmodified replacement
    # system. Apply only the reviewed, hash-locked NFC transport source delta.
    for patch in json.loads((device / 'independent/source-patches.json').read_text()):
        repository = root / patch['repository']
        actual = {name: digest((repository / name).read_bytes())
                  if (repository / name).is_file() else None for name in patch['files']}
        if all(actual[name] == hashes['after'] for name, hashes in patch['files'].items()):
            continue
        if not all(actual[name] == hashes['before'] for name, hashes in patch['files'].items()):
            raise SystemExit('Unexpected source content in ' + patch['repository'])
        path = device / 'independent' / patch['patch']
        subprocess.run(['git', '-C', str(repository), 'apply', '--check', str(path)], check=True)
        subprocess.run(['git', '-C', str(repository), 'apply', str(path)], check=True)
        if not all(digest((repository / name).read_bytes()) == hashes['after']
                   for name, hashes in patch['files'].items()):
            raise SystemExit('Applied source hash mismatch in ' + patch['repository'])
    # Derive complete defconfigs for the 3.10 build system, which does not
    # support modern config-fragment make targets. Preserve the baseline
    # defconfigs and change only the two built-in Broadcom file defaults.
    configs = root / 'kernel/meizu/m86/arch/arm64/configs'
    kernel_configs = {}
    for source in sorted(configs.glob('cm_pro5*_defconfig')):
        if source.name.endswith('_vendor_defconfig'):
            continue
        original = source.read_text()
        text = original
        for key, path in [('BCMDHD_FW_PATH', '/vendor/firmware/fw_bcmdhd.bin'),
                          ('BCMDHD_NVRAM_PATH', '/vendor/etc/wifi/bcmdhd.cal')]:
            text, count = re.subn(r'^CONFIG_' + key + r'=.*$',
                                 f'CONFIG_{key}="{path}"', text, flags=re.MULTILINE)
            if count != 1:
                raise SystemExit(f'Missing unique {key} in {source}')
        output = source.with_name(source.name.replace('_defconfig', '_vendor_defconfig'))
        output.write_text('# Generated by prepare-independent-vendor.py from '
                          + source.name + '\n' + text)
        kernel_configs[output.name] = {'base': source.name,
                                      'base_sha256': digest(source.read_bytes()),
                                      'sha256': digest(output.read_bytes())}
    (device / 'independent/kernel-configs.generated.json').write_text(
        json.dumps(kernel_configs, indent=2) + '\n')
    prepared = vendor / 'proprietary/independent'
    report = {}
    for relative, rules in lock['transforms'].items():
        original = vendor / 'proprietary' / relative
        output = prepared / relative
        data = original.read_bytes()
        for rule in rules.get('strings', []):
            before, after = rule['from'].encode(), rule['to'].encode()
            if len(after) > len(before):
                raise SystemExit(f'Path replacement grows an ELF string: {relative}')
            if data.count(before) != rule['count']:
                raise SystemExit(f'Unexpected string count in {relative}: {before!r}')
            data = data.replace(before, after + b'\0' * (len(before) - len(after)))
        output.parent.mkdir(parents=True, exist_ok=True)
        output.write_bytes(data)
        shutil.copymode(original, output)
        for name in rules.get('remove_needed', []):
            subprocess.run(['patchelf', '--remove-needed', name, str(output)], check=True)
        for name in rules.get('add_needed', []):
            subprocess.run(['patchelf', '--add-needed', name, str(output)], check=True)
        needed = subprocess.check_output(['patchelf', '--print-needed', str(output)], text=True)
        report[relative] = {'input_sha256': digest(original.read_bytes()),
                            'output_sha256': digest(output.read_bytes()),
                            'needed': needed.splitlines()}
    for source_name, dest_name in lock['makefiles'].items():
        text = (vendor / source_name).read_text()
        text = text.replace('$(TARGET_COPY_OUT_SYSTEM)', '$(TARGET_COPY_OUT_VENDOR)')
        # Keep TFA's compiled path prefix length unchanged: /etc/tfa98xx/
        # becomes /vendor/tfa/. No code/data address relocation is necessary.
        text = text.replace(':$(TARGET_COPY_OUT_VENDOR)/etc/tfa98xx/',
                            ':$(TARGET_COPY_OUT_VENDOR)/tfa/')
        for relative in lock['transforms']:
            text = text.replace(f'vendor/meizu/m86/proprietary/{relative}:',
                                f'vendor/meizu/m86/proprietary/independent/{relative}:')
        # The AOSP source effects/DRM and native OMX path own these modules.
        # Flyme extractor/effect binaries must not override the vendor variants.
        lines = []
        for line in text.splitlines():
            if any(token in line for token in lock['excluded_copy_tokens']):
                continue
            match = re.match(r'\s+vendor/meizu/m86/proprietary/([^:]+):', line)
            if match:
                source = match[1].removeprefix('independent/')
                # Firmware, configuration and secure-world TAs remain opaque
                # inputs. Ordinary userspace ELF/binaries have explicit owners.
                userspace = source.startswith(('bin/', 'lib/', 'lib64/',
                                                'vendor/lib/', 'vendor/lib64/'))
                if userspace and source not in lock['allowed_blob_sources']:
                    continue
            lines.append(line)
        # A removed final continuation item can leave a dangling backslash.
        for i in range(len(lines) - 1):
            if not lines[i + 1].startswith(('    ', '\t')):
                lines[i] = lines[i].removesuffix(' \\')
        if lines:
            lines[-1] = lines[-1].removesuffix(' \\')
        (vendor / dest_name).write_text(
            '# Generated by device/meizu/m86/tools/prepare-independent-vendor.py\n'
            + '\n'.join(lines) + '\n')
    (prepared / 'manifest.json').write_text(json.dumps(report, indent=2) + '\n')
    print(json.dumps({'transformed_blobs': len(report), 'manifest': str(prepared / 'manifest.json')}))


if __name__ == '__main__':
    main()
